/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: {{ file|fileDescriptorName }}
 *
 */

/*
 * Copyright 2017, gRPC Authors All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import Foundation
import SwiftGRPC

//-{% for service in file.services %}
public class {{ service|serviceName }}Service {
    
    //-{% for method in service.methods %}
    //-{% if method|methodIsUnary %}
    //-{% include "client-call-unary.swift" %}
    //-{% endif %}
    //-{% if method|methodIsServerStreaming %}
    //-{% include "client-call-serverstreaming.swift" %}
    //-{% endif %}
    //-{% if method|methodIsClientStreaming %}
    //-{% include "client-call-clientstreaming.swift" %}
    //-{% endif %}
    //-{% if method|methodIsBidiStreaming %}
    //-{% include "client-call-bidistreaming.swift" %}
    //-{% endif %}
    //-{% endfor %}
}
//-{% endfor %}

